### ISSUE TITLE
Reminder to order groceries

### ISSUE THREAD

**Issue by alexgleason** [Uptwinkles/twink#14]
How often does this happen again?

**Comment by marykatefain** [comment]
Bi-weekly

**Comment by alexgleason** [comment]
Damn, [node-schedule](https://github.com/node-schedule/node-schedule/blob/master/README.md) can't handle that type of logic. Again, it has to do with reference points. Two weeks from when?

It can schedule by date. I guess we can count weeks from the epoch (Jan 1, 1970) again and find whether they're even or odd.

**Comment by alexgleason** [comment]
*it can schedule by day of the week

So we can say "if it's Sunday at noon perform some logic to see if this is an even or odd week since the epoch and show the message only if it's an odd week"

**Comment by marykatefain** [comment]
Is there any reason to not do a weekly check-in on where we are with groceries? Even if we don't need a big order, it would be helpful for people to be reminded to use the grocery list board and we should move to getting produce weekly from grocer stands anyways. Doing our produce bi-weekly is not going well.
