### ISSUE TITLE
Daily Dishes reminder

### ISSUE THREAD

**Issue by marykatefain** [Uptwinkles/twink#4]
Remind the person who is on dishes to do them

**Comment by marykatefain** [comment]
Can personal reminders (reminders to one person, not to the whole house, be sent via text? The people who are the biggest problem are the people who don't check the house chat...)

**Comment by alexgleason** [comment]
We could implement something like Twilio, but it would add complexity and it's a proprietary service. Sending texts over the internet requires a bridge which usually means relying on a third party.
