### ISSUE TITLE
Send updated house code to trusted members

### ISSUE THREAD

**Issue by alexgleason** [Uptwinkles/twink#5]
Some people will have an access code to the house. This code will be rotated each month. We should keep a list of these people, and have Twink email them with the updated code each month.

**Comment by alexgleason** [comment]
Really, we could have Twink generate the code first and we'll set the code to whatever it generates.

**Comment by alexgleason** [comment]
https://www.npmjs.com/package/generate-pincode

**Comment by marykatefain** [comment]
I think we can create a Riot room for people to whom we grant house access and have the code post to that room, as well. Maybe we can possibly also set a long term resident code for roommies that does not change every month, and the rotating code can only be for outside people.

**Comment by alexgleason** [comment]
we could have a list of rooms in an array and have Twink send the code to each one. open a new issue if you want to explore this further
